package org.appdynamics.deployment.model;

public enum DeepDivePolicy {
    CONTINUING,
	SLA_FAILURE,
    TIME_SAMPLING,
    ERROR_SAMPLING,
    OCCURRENCE_SAMPLING, 
    ON_DEMAND,
    HOTSPOT,
    HOTSPOT_LEARN,
    APPLICATION_STARTUP,
    SLOW_DIAGNOSTIC_SESSION,
    ERROR_DIAGNOSTIC_SESSION,
    POLICY_FAILURE_DIAGNOSTIC_SESSION,
    DIAGNOSTIC_SESSION,
    INFLIGHT_SLOW_SESSION,
    CROSS_APP_POLICY;
}
